// This file will be auto-generated by Convex when you run: npx convex dev
// These are temporary placeholders to help with development
// Run `npx convex dev` after setting up your .env file to generate proper types

import type { AnyDataModel } from "convex/server";
import type { GenericId } from "convex/values";

// Temporary type-safe placeholders
export const api = {
  queries: {
    sites: {
      listForTenant: {} as any,
      getById: {} as any,
    },
    pages: {
      listForSite: {} as any,
      getById: {} as any,
      getByPath: {} as any,
    },
    templates: {
      listPublic: {} as any,
      listAll: {} as any,
      getById: {} as any,
    },
    media: {
      listForTenant: {} as any,
    },
    tenants: {
      getCurrent: {} as any,
    },
  },
  mutations: {
    sites: {
      create: {} as any,
      update: {} as any,
      remove: {} as any,
      publish: {} as any,
      unpublish: {} as any,
    },
    pages: {
      create: {} as any,
      update: {} as any,
      remove: {} as any,
      publish: {} as any,
    },
    media: {
      upload: {} as any,
      remove: {} as any,
    },
    tenants: {
      create: {} as any,
      update: {} as any,
    },
  },
  actions: {
    seedTemplates: {
      seed: {} as any,
    },
    fileUpload: {
      generateUploadUrl: {} as any,
    },
  },
} as const;

// Helper type for Convex IDs
export type Id<TableName extends string> = GenericId<TableName>;

