// This file will be auto-generated by Convex when you run: npx convex dev
// Run `npx convex dev` after setting up your .env file to generate proper types

import {
  query as baseQuery,
  mutation as baseMutation,
  action as baseAction,
} from "convex/server";

// Temporary exports for development
export const query = baseQuery;
export const mutation = baseMutation;
export const action = baseAction;

